<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="7" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="135" started-at="2020-04-04T16:30:23Z" finished-at="2020-04-04T16:30:23Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="135" started-at="2020-04-04T16:30:23Z" finished-at="2020-04-04T16:30:23Z">
      <class name="com.training.sanity.tests.TestNGAnnotationEx1">
        <test-method status="FAIL" signature="A()[pri:0, instance:com.training.sanity.tests.TestNGAnnotationEx1@20e2cbe0]" name="A" duration-ms="24" started-at="2020-04-04T22:00:23Z" finished-at="2020-04-04T22:00:23Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [dINAKAR] but found [vinay]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [dINAKAR] but found [vinay]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.training.sanity.tests.TestNGAnnotationEx1.A(TestNGAnnotationEx1.java:8)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- A -->
        <test-method status="PASS" signature="G()[pri:0, instance:com.training.sanity.tests.TestNGAnnotationEx1@20e2cbe0]" name="G" duration-ms="2" started-at="2020-04-04T22:00:23Z" finished-at="2020-04-04T22:00:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- G -->
        <test-method status="PASS" signature="B()[pri:0, instance:com.training.sanity.tests.TestNGAnnotationEx1@20e2cbe0]" name="B" duration-ms="5" started-at="2020-04-04T22:00:23Z" finished-at="2020-04-04T22:00:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- B -->
        <test-method status="PASS" signature="C()[pri:0, instance:com.training.sanity.tests.TestNGAnnotationEx1@20e2cbe0]" name="C" duration-ms="3" started-at="2020-04-04T22:00:23Z" finished-at="2020-04-04T22:00:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C -->
        <test-method status="PASS" signature="E()[pri:1, instance:com.training.sanity.tests.TestNGAnnotationEx1@20e2cbe0]" name="E" duration-ms="2" started-at="2020-04-04T22:00:23Z" depends-on-methods="com.training.sanity.tests.TestNGAnnotationEx1.A" finished-at="2020-04-04T22:00:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- E -->
        <test-method status="SKIP" signature="D()[pri:2, instance:com.training.sanity.tests.TestNGAnnotationEx1@20e2cbe0]" name="D" duration-ms="0" started-at="2020-04-04T22:00:23Z" depends-on-methods="com.training.sanity.tests.TestNGAnnotationEx1.A" finished-at="2020-04-04T22:00:23Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestNGAnnotationEx1.D()[pri:2, instance:com.training.sanity.tests.TestNGAnnotationEx1@20e2cbe0] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestNGAnnotationEx1.D()[pri:2, instance:com.training.sanity.tests.TestNGAnnotationEx1@20e2cbe0] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1084)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- D -->
        <test-method status="PASS" signature="F()[pri:3, instance:com.training.sanity.tests.TestNGAnnotationEx1@20e2cbe0]" name="F" duration-ms="5" started-at="2020-04-04T22:00:23Z" finished-at="2020-04-04T22:00:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- F -->
      </class> <!-- com.training.sanity.tests.TestNGAnnotationEx1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
